#!/usr/bin/env python3
"""Generate the viewer-safe, presentation-only v05 card text catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def csharp(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "\\n") + '"'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    document = json.loads(args.input.read_text(encoding="utf-8"))
    cards = list(document["cards"]) + list(document["tokens"])
    cards.sort(key=lambda card: card["design_id"])

    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by scripts/design/generate_product_client_catalog.py. Do not edit by hand.",
        "#nullable enable",
        "namespace Scgs.GodotClient.Presentation;",
        "",
        "internal sealed record ProductCardTextEntry(",
        "    string DesignId,",
        "    string Name,",
        "    string ProfessionId,",
        "    string SeriesId,",
        "    bool Neutral,",
        "    string Availability,",
        "    string CanonicalRulesText);",
        "",
        "internal static class ProductCardTextCatalog",
        "{",
        "    private static readonly IReadOnlyDictionary<string, ProductCardTextEntry> EntriesById =",
        "        new Dictionary<string, ProductCardTextEntry>(StringComparer.Ordinal)",
        "        {",
    ]
    for card in cards:
        lines.extend(
            [
                f"            [{csharp(card['design_id'])}] = new(",
                f"                {csharp(card['design_id'])},",
                f"                {csharp(card['name'])},",
                f"                {csharp(card['profession_id'])},",
                f"                {csharp(card['series_id'])},",
                f"                {str(bool(card.get('neutral', False))).lower()},",
                f"                {csharp(card.get('availability', 'token'))},",
                f"                {csharp(card['canonical_rules_text'])}),",
            ]
        )
    lines.extend(
        [
            "        };",
            "",
            "    internal static IReadOnlyCollection<ProductCardTextEntry> Entries => EntriesById.Values.ToArray();",
            "",
            "    internal static ProductCardTextEntry? Find(string? designId) =>",
            "        string.IsNullOrWhiteSpace(designId) ? null : EntriesById.GetValueOrDefault(designId);",
            "}",
            "",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
